"""
Author: L. Saetta
Date last modified: 2026-04-21
License: MIT
Description: FastAPI service exposing HTTP endpoints to invoke the OCI tool-calling assistant.
"""

import asyncio
import json
import os
from pathlib import Path
from typing import Any, AsyncIterator, Dict, List, Optional

from dotenv import load_dotenv
from fastapi import FastAPI, HTTPException
from fastapi.middleware.cors import CORSMiddleware
from pydantic import BaseModel, Field
from starlette.responses import StreamingResponse

from agent.tool_calling_agent import ConsumptionToolCallingAgent

load_dotenv()

DEFAULT_CORS_ORIGINS = ["http://localhost:3000", "http://127.0.0.1:3000"]
DEFAULT_MCP_CONFIG_PATH = str(
    Path(__file__).resolve().parents[1] / "config" / "mcp_servers.json"
)


class ChatMessage(BaseModel):
    """Single chat message used as conversation history input.

    Attributes:
        role: Message role (`system`, `user`, or `assistant`).
        content: Message textual content.
    """

    role: str = Field(..., description="Message role, e.g. user or assistant.")
    content: str = Field(..., description="Message content text.")


class AgentInvokeRequest(BaseModel):
    """Request body for assistant invocation.

    Attributes:
        message: Current user request to process.
        history: Optional prior conversation messages.
    """

    message: str = Field(..., description="Current user prompt for the agent.")
    history: Optional[List[ChatMessage]] = Field(
        default=None,
        description="Optional previous conversation turns to preserve context.",
    )


class AgentInvokeResponse(BaseModel):
    """HTTP response payload returned by the assistant endpoint.

    Attributes:
        answer: Final textual answer generated by the tool-calling loop.
        mcp_servers: Names of MCP servers consulted by the agent.
        tool_count: Number of tools loaded across configured MCP servers.
        messages: Raw LangChain message payload for debugging/integration use.
    """

    answer: str
    mcp_servers: List[str]
    tool_count: int
    messages: List[Any]


app = FastAPI(
    title="OCI Consumption Agent API",
    version="0.1.0",
    description=(
        "HTTP API for invoking the OCI consumption assistant based on "
        "LangChain tool-calling and MCP tools."
    ),
)


def _parse_cors_origins(raw_value: Optional[str]) -> List[str]:
    """Parse comma-separated CORS origins.

    Args:
        raw_value: Environment variable value for `CORS_ALLOW_ORIGINS`.

    Returns:
        List of allowed origins. Falls back to defaults when not provided.
    """
    if not raw_value:
        return DEFAULT_CORS_ORIGINS

    origins = [origin.strip() for origin in raw_value.split(",") if origin.strip()]
    return origins or DEFAULT_CORS_ORIGINS


cors_origins = _parse_cors_origins(os.getenv("CORS_ALLOW_ORIGINS"))
app.add_middleware(
    CORSMiddleware,
    allow_origins=cors_origins,
    allow_credentials=True,
    allow_methods=["*"],
    allow_headers=["*"],
)

agent_service = ConsumptionToolCallingAgent(
    mcp_config_path=os.getenv("MCP_SERVERS_CONFIG", DEFAULT_MCP_CONFIG_PATH),
)


@app.get("/health")
async def health() -> Dict[str, str]:
    """Return health status for API uptime checks.

    Returns:
        Dictionary containing service status.
    """
    return {"status": "ok"}


@app.post("/agent/invoke", response_model=AgentInvokeResponse)
async def invoke_agent(payload: AgentInvokeRequest) -> AgentInvokeResponse:
    """Invoke the tool-calling agent through HTTP.

    This endpoint triggers the complete agent loop:
    1. load tools from configured MCP servers;
    2. run LangChain tool-calling iterations;
    3. return final answer and execution metadata.

    Args:
        payload: Input request including the current message and optional history.

    Returns:
        `AgentInvokeResponse` with answer, loaded servers, tool count, and messages.

    Raises:
        HTTPException: On validation or runtime errors during agent execution.
    """
    try:
        history = (
            [{"role": item.role, "content": item.content} for item in payload.history]
            if payload.history
            else None
        )
        result = await agent_service.invoke(
            user_message=payload.message,
            history=history,
        )
        return AgentInvokeResponse(**result)
    except ValueError as exc:
        raise HTTPException(status_code=400, detail=str(exc)) from exc
    except Exception as exc:  # pragma: no cover - runtime integration errors
        raise HTTPException(
            status_code=500, detail=f"Agent invocation failed: {exc}"
        ) from exc


def _to_sse_event(event: str, data: Dict[str, Any]) -> str:
    """Serialize one SSE event as a text frame.

    Args:
        event: Event name.
        data: JSON-serializable payload.

    Returns:
        SSE frame string with event and data lines.
    """
    return f"event: {event}\ndata: {json.dumps(data, ensure_ascii=False)}\n\n"


def _chunk_text(text: str, chunk_size: int = 120) -> List[str]:
    """Split text in fixed-size chunks for progressive SSE delivery.

    Args:
        text: Text to split.
        chunk_size: Maximum characters per chunk.

    Returns:
        List of text chunks preserving original order.
    """
    if not text:
        return []
    return [text[index : index + chunk_size] for index in range(0, len(text), chunk_size)]


@app.post("/agent/invoke/stream")
async def invoke_agent_stream(payload: AgentInvokeRequest) -> StreamingResponse:
    """Invoke the tool-calling agent and stream the final answer over SSE.

    The endpoint executes the same tool-calling workflow as `/agent/invoke`, then
    streams the final answer in chunks as `token` events to support incremental
    rendering in web clients.

    Args:
        payload: Input request including current message and optional history.

    Returns:
        StreamingResponse emitting SSE events:
        - `start`: request accepted
        - `token`: partial answer chunk
        - `final`: final metadata and full answer
        - `error`: execution error details
    """

    async def event_stream() -> AsyncIterator[str]:
        yield _to_sse_event("start", {"status": "accepted"})

        try:
            history = (
                [{"role": item.role, "content": item.content} for item in payload.history]
                if payload.history
                else None
            )
            result = await agent_service.invoke(
                user_message=payload.message,
                history=history,
            )
            answer = result.get("answer", "")

            for part in _chunk_text(answer):
                yield _to_sse_event("token", {"text": part})
                await asyncio.sleep(0)

            yield _to_sse_event(
                "final",
                {
                    "answer": answer,
                    "mcp_servers": result.get("mcp_servers", []),
                    "tool_count": result.get("tool_count", 0),
                },
            )
        except Exception as exc:  # pragma: no cover - runtime integration errors
            yield _to_sse_event("error", {"detail": f"Agent invocation failed: {exc}"})

    return StreamingResponse(
        event_stream(),
        media_type="text/event-stream",
        headers={
            "Cache-Control": "no-cache",
            "Connection": "keep-alive",
            "X-Accel-Buffering": "no",
        },
    )
